<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="VisuInit" Id="{f250eaae-ddf3-4905-b7d9-e7cd5944ef1b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM VisuInit
VAR_INPUT
	TFHandler : TextfieldInputHandler;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//VisuElems.g_VisuEventManager.SetEditBoxEventHandler(handler := TFHandler);]]></ST>
    </Implementation>
    <LineIds Name="VisuInit">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>