<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="P00_Task_Fast" Id="{91a6d0eb-8720-440f-af9c-73126ec61acc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P00_Task_Fast
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
Task_Fast_LH();
Task_Fast_TB();]]></ST>
    </Implementation>
    <LineIds Name="P00_Task_Fast">
      <LineId Id="6" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>