<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="P02_P2P" Id="{65144f6b-0d8b-41ed-8fc7-ccd91a54ba08}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P02_P2P
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//P2P_ST300_MODBUS();
P2P_LH();
P2P_TB();]]></ST>
    </Implementation>
    <LineIds Name="P02_P2P">
      <LineId Id="6" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>