<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{371f4e99-333a-4563-9f26-aefdbf01b04d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	tst_out : BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
GVL_TEST.TST_OUT := tst_out;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>