<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="P93_Setting" Id="{291d468a-e342-4faf-8035-4ed6f7eda84b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P93_Setting
VAR

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="P93_Setting">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>